spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/wulijianz/springcloud/
          searchPaths: config-server/src/main/resources #searchPaths 表示目录
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
